// <auto-generated />
using BiographicalDetails.Infrastructure.Sqlite.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiographicalDetails.Infrastructure.Sqlite.Migrations
{
    [DbContext(typeof(BiographicalDataDbContext))]
    [Migration("20251128010718_EnsureForeignKeys")]
    partial class EnsureForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BiographicalDetails.EntityModels.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImmigrationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelOfStudy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BiographicalDetails.EntityModels.UserPronounEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredPronouns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPronouns");
                });

            modelBuilder.Entity("BiographicalDetails.EntityModels.UserSinEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialInsuranceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSins");
                });

            modelBuilder.Entity("BiographicalDetails.EntityModels.UserUciEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueClientIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserUcis");
                });

            modelBuilder.Entity("BiographicalDetails.EntityModels.UserPronounEntity", b =>
                {
                    b.HasOne("BiographicalDetails.EntityModels.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("BiographicalDetails.EntityModels.UserPronounEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiographicalDetails.EntityModels.UserSinEntity", b =>
                {
                    b.HasOne("BiographicalDetails.EntityModels.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("BiographicalDetails.EntityModels.UserSinEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiographicalDetails.EntityModels.UserUciEntity", b =>
                {
                    b.HasOne("BiographicalDetails.EntityModels.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("BiographicalDetails.EntityModels.UserUciEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
