// <auto-generated />
using BiographicalDetails.Infrastructure.Sql.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiographicalDetails.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(BiographicalDataDbContext))]
    partial class BiographicalDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiographicalDetails.Domain.BiographicalDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ImmigrationStatus")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LevelOfStudy")
                        .HasColumnType("int");

                    b.Property<string>("PreferredPronouns")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SocialInsuranceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UniqueClientIdentifier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BiographicalDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan@test.com",
                            FirstName = "Ivan",
                            ImmigrationStatus = 6,
                            LastName = "Perez",
                            LevelOfStudy = 0,
                            PreferredPronouns = "He/Him",
                            UniqueClientIdentifier = "0000-0000"
                        },
                        new
                        {
                            Id = 2,
                            Email = "juan@yay.com",
                            FirstName = "Juan",
                            ImmigrationStatus = 0,
                            LastName = "Perez",
                            LevelOfStudy = 1,
                            PreferredPronouns = "They/Them",
                            SocialInsuranceNumber = "000-000-000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
